#!/bin/bash
# This script compiles a C source file into an object file using the gcc compiler.
# The source file to be compiled is specified by the environment variable CFILE.
# The -c flag tells gcc to compile the source file without linking.
gcc -c $CFILE
